In [6]:
import pandas as pd
df = pd.read_csv(r"C:\Users\pattargv\Downloads\Test_Data\salary100k.csv")
df.head(3)

company               job     degree  salary_more_then_100k
0  google   sales executive  bachelors                      0
1  google   sales executive    masters                      0
2  google  business manager  bachelors                      1

In [4]:
inputs = df.drop('salary_more_then_100k', axis = "columns")
target = df["salary_more_then_100k"]

In [5]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [10]:
inputs["company_n"] = le_company.fit_transform(inputs["company"])
inputs["job_n"] = le_job.fit_transform(inputs["job"])
inputs["degree_n"] = le_degree.fit_transform(inputs["degree"])
inputs.head()

company                  job     degree  company_n  job_n  degree_n
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

In [12]:
inputs_n = inputs.drop(["company","job", "degree"], axis = "columns")

In [13]:
inputs_n.head()

company_n  job_n  degree_n
0          2      2         0
1          2      2         1
2          2      0         0
3          2      0         1
4          2      1         0

In [14]:
from sklearn import tree

In [15]:
model = tree.DecisionTreeClassifier()

In [16]:
model.fit(inputs_n, target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [17]:
model.score(inputs_n, target)

1.0

In [19]:
model.predict([[2,2,1]])

array([0], dtype=int64)

In [20]:
model.predict([[2,0,0]])

array([1], dtype=int64)

In [21]:
Excercise

NameError: name 'Excercise' is not defined

In [69]:
df = pd.read_csv(r"C:\Users\pattargv\Downloads\Test_Data\titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [70]:
inputs = df.drop(["PassengerId", "Survived", "Name", "SibSp", "Parch", "Ticket", "Cabin", "Embarked"], axis = "columns")
inputs.head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [71]:
from sklearn.preprocessing import LabelEncoder

le_sex = LabelEncoder()

In [72]:
inputs["sex_n"] = le_sex.fit_transform(inputs["Sex"])
inputs.head()

Pclass     Sex   Age     Fare  sex_n
0       3    male  22.0   7.2500      1
1       1  female  38.0  71.2833      0
2       3  female  26.0   7.9250      0
3       1  female  35.0  53.1000      0
4       3    male  35.0   8.0500      1

In [88]:
inputs_n = inputs.drop("Sex", axis = "columns")
inputs_n.head(10)

Pclass   Age     Fare  sex_n
0       3  22.0   7.2500      1
1       1  38.0  71.2833      0
2       3  26.0   7.9250      0
3       1  35.0  53.1000      0
4       3  35.0   8.0500      1
5       3   NaN   8.4583      1
6       1  54.0  51.8625      1
7       3   2.0  21.0750      1
8       3  27.0  11.1333      0
9       2  14.0  30.0708      0

In [74]:
target = df["Survived"]
#target = target.dropna("NaN")
target.head(10)

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: Survived, dtype: int64

In [78]:
import math
age_mean = math.floor(inputs_n.Age.mean())
age_mean

29

In [79]:
inputs_n.Age = inputs_n.Age.fillna(age_mean)

In [81]:
inputs_n.head(25)

Pclass        Age     Fare  sex_n
0        3  22.000000   7.2500      1
1        1  38.000000  71.2833      0
2        3  26.000000   7.9250      0
3        1  35.000000  53.1000      0
4        3  35.000000   8.0500      1
5        3  29.699118   8.4583      1
6        1  54.000000  51.8625      1
7        3   2.000000  21.0750      1
8        3  27.000000  11.1333      0
9        2  14.000000  30.0708      0
10       3   4.000000  16.7000      0
11       1  58.000000  26.5500      0
12       3  20.000000   8.0500      1
13       3  39.000000  31.2750      1
14       3  14.000000   7.8542      0
15       2  55.000000  16.0000      0
16       3   2.000000  29.1250      1
17       2  29.699118  13.0000      1
18       3  31.000000  18.0000      0
19       3  29.699118   7.2250      0
20       2  35.000000  26.0000      1
21       2  34.000000  13.0000      1
22       3  15.000000   8.0292      0
23       1  28.000000  35.5000      1
24       3   8.000000  21.0750      0

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
X_train, X_test, y_train,y_test = train_test_split(inputs_n, target)

In [52]:
len(y_train)

668

In [37]:
len(y_test)

223

In [110]:
model = tree.DecisionTreeClassifier(criterion = "entropy")

In [111]:
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [86]:
model.predict(X_test)

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0], dtype=int64)

In [104]:
model.predict([[2, 25, 26, 1]])

array([0], dtype=int64)

In [105]:
model.predict([[3, 32, 7.75, 0]])

array([0], dtype=int64)

In [106]:
model.predict([[1, 26, 30, 0]])

array([1], dtype=int64)

In [107]:
model.predict([[1, 19, 30, 1]])

array([1], dtype=int64)

In [108]:
model.predict([[1, 56, 83.1583, 1]])

array([0], dtype=int64)

In [109]:
model.predict([[2, 25, 26, 1]])

array([0], dtype=int64)

In [87]:
model.score(X_train,y_train)

0.9820359281437125

In [112]:
model.score(X_train,y_train)

0.9925149700598802

In [113]:
model.predict([[2, 25, 26, 1]])

array([0], dtype=int64)

In [114]:
model.predict([[3, 32, 7.75, 0]])

array([0], dtype=int64)

In [115]:
model.predict([[1, 26, 30, 0]])

array([1], dtype=int64)

In [116]:
model.predict([[1, 19, 30, 1]])

array([0], dtype=int64)

In [117]:
model.predict([[1, 56, 83.1583, 1]])

array([1], dtype=int64)

In [118]:
model.predict([[2, 25, 26, 1]])

array([0], dtype=int64)

In [90]:
age_interpol = inputs_n.interpolate()
age_interpol.head(20)

Pclass   Age     Fare  sex_n
0        3  22.0   7.2500      1
1        1  38.0  71.2833      0
2        3  26.0   7.9250      0
3        1  35.0  53.1000      0
4        3  35.0   8.0500      1
5        3  44.5   8.4583      1
6        1  54.0  51.8625      1
7        3   2.0  21.0750      1
8        3  27.0  11.1333      0
9        2  14.0  30.0708      0
10       3   4.0  16.7000      0
11       1  58.0  26.5500      0
12       3  20.0   8.0500      1
13       3  39.0  31.2750      1
14       3  14.0   7.8542      0
15       2  55.0  16.0000      0
16       3   2.0  29.1250      1
17       2  16.5  13.0000      1
18       3  31.0  18.0000      0
19       3  33.0   7.2250      0

In [91]:
X_train, X_test, y_train,y_test = train_test_split(age_interpol, target)

In [121]:
new_model = tree.DecisionTreeClassifier()

new_model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [125]:
new_model.score(X_test, y_test)

0.7982062780269058

In [95]:
new_model.predict(X_test)

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0], dtype=int64)

In [96]:
len(X_test)

223

In [98]:
new_model.predict([[3, 32, 7.75, 0]])

array([0], dtype=int64)

In [99]:
new_model.predict([[1, 26, 30, 0]])

array([1], dtype=int64)

In [103]:
new_model.predict([[2, 25, 26, 1]])

array([0], dtype=int64)

In [126]:
t1 = new_model.get_depth()
t1

AttributeError: 'DecisionTreeClassifier' object has no attribute 'get_depth'

In [123]:
new_model.predict_prob(X_train)

AttributeError: 'DecisionTreeClassifier' object has no attribute 'predict_prob'

In [124]:
new_model.get_n_leaves()

AttributeError: 'DecisionTreeClassifier' object has no attribute 'get_n_leaves'

In [127]:
n_nodes = new_model.tree_.node_count

In [129]:
import numpy as np
node_depth = np.zeros(shape=n_nodes, dtype=np.int64)

In [130]:
is_leaves = np.zeros(shape=n_nodes, dtype=bool)

In [131]:
node_depth

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,